### ISSUE TITLE
Матрица ранжирования

### ISSUE THREAD

**Issue by RadchukOleksandr** [kievpribor/WisiNet2_issues#4]
При выделении наименования строки/колонки должна выделяться другим цветом вся строка/колонка, а также все строки/колонки с которыми пересекается данная строка/колонка (то есть там где галочки стоят)

**Comment by MykolaLukashchuk** [comment]
Выделять строку/колонку по нажатию реализовать достаточно просто.
С пересечениями сложнее, как быть с пересечениями пересечений? Их нужно подсвечивать?

**Comment by RadchukOleksandr** [comment]
Нет. Мы выделяем наименование строки. Подсвечивается, например синим цветом, вся строчка. При этом все колонки которые имеют общие флажки с этой строкой тоже подсвечиваются.

**Comment by MykolaLukashchuk** [comment]
Done! v0.12.001
